name: ci

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true

      - run: ./build.sh

